[package]
name = "fecc_cli"
version = "0.2.1"
edition = "2024"

[dependencies]
fecc_core = { workspace = true }
image = { workspace = true, features = ["png"] }
tokio = { workspace = true, features = ["full"] }
log = { workspace = true }
strum = { workspace = true }
simple_logger = { workspace = true }
