[package]
name = "fe_character_creator"
version = "0.2.1"
authors = ["aidan-es"]
edition = "2024"
default-run = "fe_character_creator"


[[bin]]
name = "fe_character_creator"
path = "src/main.rs"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]


[dependencies]
egui = { workspace = true }
fecc_core = { workspace = true }
eframe = { workspace = true, features = ["persistence"] }
log = { workspace = true }
egui_extras = { workspace = true, features = ["svg"] }
image = { workspace = true, features = ["png"] }
strum_macros = { workspace = true }
rfd = { workspace = true }
serde = { workspace = true, features = ["derive"] }
futures-channel = { workspace = true }
wasm-bindgen-futures = { workspace = true }
futures-util = { workspace = true }
strum = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
serde_json = { workspace = true }
egui-notify = { workspace = true }
egui_commonmark = { workspace = true }
pulldown-cmark = { workspace = true } # For building HTML pages
itertools = { workspace = true }
ahash = { workspace = true }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = { workspace = true }
fern = { workspace = true }
dirs-next = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }


# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
serde-wasm-bindgen = { workspace = true }
getrandom = { workspace = true, features = ["wasm_js"] }
getrandom_03 = { workspace = true, features = ["wasm_js"] } #Requied to enable wasm_js for the older getrandom still used by ahash


[build-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
