name: Deploy to Firebase Hosting on merge
on:
  release:
    types: [ published ] # Runs when you click "Publish Release" in GitHub UI

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Cache Rust dependencies (Project)
        uses: swatinem/rust-cache@v2

      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'v0.21.14' # If changed, update CI and firebase pull request also

      - name: Build with Trunk
        working-directory: fecc_gui
        run: trunk build --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FECHARACTERCREATOR }}
          channelId: live
          projectId: fecharactercreator
